version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - ./mvnw verify sonar:sonar -Dsonar.branch.name=$CODEBUILD_WEBHOOK_HEAD_REF
  post_build:
    commands:
      - echo Build completed on `date`

reports:
  # unit tests:
  SurefireReports:
    files:
      - 'TEST-*.xml'
    base-directory: target/surefire-reports